### ISSUE TITLE
Maintaining a swiftmailer fork

### ISSUE THREAD

**Issue by alquerci** [FriendsOfSymfony1/swiftmailer#14]
"Main purpose", meaning "reason for being" or "reason to be".

As a contributor, **in order** to avoid wasting time on things that do not contribute to the main purpose of this repository.

A visible purpose can help focus on the most important and vital issues.
The main purpose may be well visible, to avoid any confusion.

**Comment by thirsch** [comment]
For me, the main purpose is to fix deprecations and make this lib running under upcoming php versions as long as it's feasible with small adjustments. For 8.2 and 8.3 everything is already done and no further work needed. 

Personally, I'm not sure, if phpcs and other steps are really necessary, as I think it's better to use the time to migrate to symfony/mailer or any other actively maintained mailing solution.

What do you think about the main purpose, @alquerci, @thePanz, @connorhu?

**Comment by connorhu** [comment]
Deprecation fixing. 

https://symfony.com/blog/the-end-of-swiftmailer

“Migrating from Swiftmailer to Symfony Mailer is a relatively easy task as the concepts are the same between the two projects.”

We should start work on this.

**Comment by alquerci** [comment]
To reformulate with my words.

Main purpose: "Supports same PHP versions as latest FriendsOfSymfony1/symfony1"

In practice: For each PHP version, the test suite must pass. Where a deprecation will fail, the build.

If test suite pass, there is nothing to do.

**Comment by thePanz** [comment]
> To reformulate with my words.
> 
> Main purpose: "Supports same PHP versions as latest FriendsOfSymfony1/symfony1"
> 
> In practice: For each PHP version, the test suite must pass. Where a deprecation will fail, the build.
> 
> If test suite pass, there is nothing to do.

We should formulate it differently, without a reference to SF1.

We should mwntuin:
- which versions of PHP do we support?
- what do we do with BC breaks?
- what about new features?
- what about bugfixes in the original code? (Should we create issues from the legacy tracker to GitHub?)

This should be a discussion , not an issue IMO
